### ISSUE TITLE
How to deal with discriminated union types?

### ISSUE THREAD

**Issue by C-Higgins** [davidgilbertson/react-recollect#124]
```js
type State = {something: number} &
  ( {
    state: "loading"
    result: null
    error: null
  }
  | {
    state: "error"
    result: null,
    error: any
  }
  | {
    state: "done"
    result: Result[]
    error: null
  })

function setLoading(){
  store.state = "loading"
  store.result = null
  store.error = 'oops' // this is allowed
}
```

Because the state properties are set individually, there is no way to group them into a union type. You'll be able to set any property to any of its unioned types. The only way I can think of is to always update the whole subtree at once, but now we're back at redux-like syntax:

```
function setLoading(){
  store = {
    ...store,
    state: "loading",
    result: null,
    error: 'oops' // correctly gives type error 
  }
}
```

But obviously no one using this library wants to write stuff like that. Any ideas?

**Comment by davidgilbertson** [comment]
Can you put those related properties into their own object? Assuming a store like this:

```ts
type Response =
  | {
      state: 'loading';
      result: null;
      error: null;
    }
  | {
      state: 'error';
      result: null;
      error: any;
    }
  | {
      state: 'done';
      result: Result[];
      error: null;
    };

declare module 'react-recollect' {
  interface Store {
    response: Response
  }
}
```

You can set all properties at once like so:

```ts
store.response = {
  state: 'loading',
  result: null,
  error: 'oops', // <- will be an error
};
```

If you want to set multiple values at once as a shallow merge, you can use `Object.assign()`, but will need `as` to enforce type checking.

```ts
Object.assign(store.response, {
  state: 'done',
  result: null, // <- will be an error
  error: null,
} as Response);
```

Or partial:
```ts
Object.assign(store.response, {
  state: 'done',
  result: [],
} as Partial<Response>);
```

I think putting the properties at the top level of the store (as in your example) works too, with `Object.assign(store, newProps)` but is fiddlier to type.

**Comment by davidgilbertson** [comment]
@C-Higgins I've closed this, let me know if there's anything else I can help with
