### ISSUE TITLE
__RR__.getStore is not a function

### ISSUE THREAD

**Issue by shivam1283** [davidgilbertson/react-recollect#129]
Hi ,

I have recently using react-recollect and I was trying to debug. I was trying to access the store in console using __RR__.getStore but got the error as mentioned above. I also called __RR__.debugOn().

Please help me out here.

Thanks in advance,

Shivam

**Comment by davidgilbertson** [comment]
This is because getStore is not a function.

`__RR__.internals.store` will log the store.

See the documentation of `__RR__` for more: https://github.com/davidgilbertson/react-recollect#window__rr__

`RR.debugOn()` will also not work as it's missing the underscores around the 'RR'.
