### ISSUE TITLE
Is this project is still active?

### ISSUE THREAD

**Issue by serchavalos** [davidgilbertson/react-recollect#139]
If so, I would like to contribute

**Comment by davidgilbertson** [comment]
It's not exactly active, but I'm happy to chat about contributions. What did you have in mind?

**Comment by serchavalos** [comment]
Nothing so far; I'm still reading the source code and catching up.

After that, I might just do minor tasks like upgrading dependencies or converting demo app to TypeScript, etc. And then I'll use `recollect` for one of my pet projects to get the consumer perspective.

Just wanted to make sure any pull request won't be overlooked.

Great library by the way! I'm having a blast going through the internals. Let's keep it active
