### ISSUE TITLE
Question: How would you create "selectors"

### ISSUE THREAD

**Issue by danawoodman** [davidgilbertson/react-recollect#36]
Would using something like reselect be possible with recollect? For example, creating a selector that filters a list of items in your store and that automatically updates when the store changes?

Is there another way to approach this?

Thanks and keep up the good work!

**Comment by davidgilbertson** [comment]
Well it's funny, I just added a doc last night all about selectors. https://github.com/davidgilbertson/react-recollect/blob/master/docs/selector-pattern.md

I haven't tested with reselect though.

**Comment by danawoodman** [comment]
Haha nice! A psychic you are!

This is golden 😆 

> When the people that made JavaScript were coming up with array methods, for each one they would do a shot of tequila and flip a coin to decide whether or not it should mutate the original array
