### ISSUE TITLE
Not SSR safe

### ISSUE THREAD

**Issue by stepanh** [davidgilbertson/react-recollect#38]
Rendering a component with `store` server side ends in an explosion:
```
ReferenceError: localStorage is not defined
```

_Note:_ I guess that on server, `store` could be just a plain object, no need for proxy.

**Comment by davidgilbertson** [comment]
Thanks for this.

I've got a task #28 to sort something else out to get SSR rendering, which is coming up soon: https://github.com/davidgilbertson/react-recollect/projects/1

I've added a note to that issue and will close this one.

Good point about plain object on the server, I'll look into ditching it.
