### ISSUE TITLE
Create ToDoMVC style TODO app

### ISSUE THREAD

**Issue by davidgilbertson** [davidgilbertson/react-recollect#43]
There's not much point actually submitting something to TodoMVC, but doing a CodeSandbox with all the features might be a useful learning tool.

**Comment by danawoodman** [comment]
Why do you think there is no point submitting to TodoMVC? Seems a good way to promote the project?

**Comment by davidgilbertson** [comment]
Just that in my head nobody uses it any more. It's still React 0.13! Also there's no React-Redux or React-MobX

**Comment by danawoodman** [comment]
Oh weird! That’s honestly a surprise to me. That said, prob best to just focus on docs, library improvements and gaining adoption!

**Comment by davidgilbertson** [comment]
Done, sort of.

TODO apps aren't great environments for testing performance because each item is so tiny. For something more indicative of a real app, I've made a 'products' page with a decent amount of DOM for each array item, and some actions that iterate over the array to update various props.

https://codesandbox.io/s/lxy1mz200l
