### ISSUE TITLE
DevTools

### ISSUE THREAD

**Issue by dijs** [davidgilbertson/react-recollect#57]
Before you ask... I read the readme.

```Use __RR__.debugOn() to turn on debugging. The setting is stored in local storage, so will persist while you sleep. You can combine this with Chrome's console filtering, for example to only see 'UPDATE' or 'SET' events. Who needs professional, well made dev tools extensions!```

Yes, this is awesome. EXCEPT, Google freaking ripped out the filtering feature in the console [read more](https://groups.google.com/forum/m/#!topic/google-chrome-developer-tools/kH3FiDLlsFg). So that really makes debugging in the console very difficult.

Any plans on reusing the popular redux dev tools to show changes in the store? MobX does this, and it works really well.

If you don't have time, just let me know and I may be able to spend some time looking into it.

Lastly, this is a really great little library. I have already used it on two of my personal projects. Thank you for your hard work!

**Comment by dijs** [comment]
Ahhh, 🤦...

I just tried using regex in the console filter and it worked.

For those who find this and need it:

```/UPDATE|SET/```

Anyways, getting this sucker on the redux devtools would still be highly beneficial, so I won't close this issue just yet.

**Comment by dijs** [comment]
Well... That was super easy.

In any component you use `collect` on, you can import and add an inspector:

```js
import { inspectProps } from 'react-inspect-props';
...


export default collect(inspectProps('Inspector')(Component));
```

Then just make sure you have the Google Chrome Redux DevTools installed.

**Comment by davidgilbertson** [comment]
Hey, `react-inspect-props` is great! Thanks for sharing, and thanks for offering to look into it.

In some circumstances, you also might find useful `afterChange` which would let you conditionally log updates to the console. For example:
```js
import { afterChange } from 'react-recollect';

afterChange(props => {
  if (props.propPath.includes('products')) {
    props.components.forEach(component => {
      console.log(`Updated "${component._name}" because "${props.propPath}" changed`);
    });
  }
});
```

Or even use a [live expression](https://developers.google.com/web/updates/2018/08/devtools#watch) to watch something very specific, like `__RR__.getStore().products.filter(product => product.favorite).length`.
