### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by charmstead** [davidgilbertson/react-recollect#59]
Why does the associated component always seem to get this error 
> RangeError: Maximum call stack size exceeded

whenever i want to set a new value for an array store property. Please, check the code snippet below
` 
 axios.delete('/v1/order/deleteorder/' + id)
            .then(res => {
                let orders = this.props.store.orders;
                this.props.store.orders=orders.filter(({_id})=>{
                    return _id !==id
                })   
                // this.props.history.location('/order')
            })
`

I wish to filter the store.order and set new value after deleting an order but i get that error.
Please do let me know what i am doing wrong.

**Comment by charmstead** [comment]
I will appreciate any feedback i can get.

**Comment by silverwind** [comment]
I don't see anything inherently wrong with your code, but could you provide a standalone test case on https://codesandbox.io/s/new?
