### ISSUE TITLE
Clarification on using the store in React components

### ISSUE THREAD

**Issue by garciaalvaro** [davidgilbertson/react-recollect#60]
Great plugin, I have been testing it for some days and it works great.
Just a clarification on which store to use with a collected React component (I am a bit confused on this).

As I understood from the documentation a component "reading" from the store should be collected and use the store that the HOC provides in the props.

My question is when this component makes changes to the store (that will affect other components), should it make them to the store from props, the one imported from the plugin or it doesn't matter?
A follow up question is if the component only modifies the store but doesn't read from it, should it be collected? And if so, the first question again, which store to use?

Thanks!

**Comment by davidgilbertson** [comment]
@garciaalvaro FYI in 4.0.0 there is now an error if you try to read from the 'wrong' store.

When making changes, it doesn't matter which version of the store. The only rule is "when reading inside a collected component, use the store passed to that component as a prop".
