### ISSUE TITLE
ReferenceError: window is not defined in Node.js

### ISSUE THREAD

**Issue by sashikn** [davidgilbertson/react-recollect#74]
How does it work in nextJS

**Comment by davidgilbertson** [comment]
That's quite a broad question. What have you tried? Have you read the readme, particularly the section on server rendering?

**Comment by linkors** [comment]
When using `react-recollect` in next js I got `ReferenceError: window is not defined`. It seems like the build contains `window` object as seen below.
![image](https://user-images.githubusercontent.com/42864780/75216307-25f25100-57c6-11ea-83e5-233735a60207.png)

**Comment by davidgilbertson** [comment]
Thanks @linkors. It seems like the bundler is doing this (and the test runner adds `window` so I didn't spot the problem).

I'll fix and add some tests.

**Comment by sashikn** [comment]
So when can we expect this ???

**Comment by davidgilbertson** [comment]
It's next in the queue, should be released in a week or two.

**Comment by davidgilbertson** [comment]
@sashikn and @linkors this is fixed in the latest release, v4.0.1 https://github.com/davidgilbertson/react-recollect/releases/tag/v4.0.1
