### ISSUE TITLE
__RR__.debugOn broken

### ISSUE THREAD

**Issue by uidev547** [davidgilbertson/react-recollect#9]
![screenshot from 2018-11-14 17-40-41](https://user-images.githubusercontent.com/6046714/48481758-a640ad00-e834-11e8-9306-5ff3eab0b07c.png)

**Comment by davidgilbertson** [comment]
Interesting, it works for me.

A few questions:

1. What browser? That's not IE is it? IE isn't supported.
2. If you go into [this code sandbox](https://codesandbox.io/s/lxy1mz200l), and set the scope of the console to the sandbox, and try `__RR__.debugOn()` there, does it work for you?
![image](https://user-images.githubusercontent.com/4443482/48513106-168c1480-e8af-11e8-8929-ba63b8b1c113.png)
3. What version of `react-recollect`?

**Comment by danawoodman** [comment]
Also worked for me on the latest version of recollect:

```js
__RR__.debugOn()
```
![](https://cl.ly/822b5e859508/Screen%20Shot%202018-11-14%20at%203.19.02%20PM.png)

**Comment by uidev547** [comment]
It is working fine latest chrome browser. I think issue with browser version. Closing the issue
