### ISSUE TITLE
Update the store without re-rendering elements

### ISSUE THREAD

**Issue by Kycermann** [davidgilbertson/react-recollect#90]
Thank you for the project.

I have a HTML text area and I store its contents in the store every time the value changes. The re-rendering for every character causes visible lag.

```
<div className="CodeArea">
  <CodeMirror
    value={store.code}
    options={{
      mode: "xml",
      lineNumbers: true
    }}
    onChange={(editor, data, value) => {
      store.code = value;
    }}
  />
</div>
```

How do I go about preventing the re-rendering using react-recollect?

**Comment by davidgilbertson** [comment]
If you want to use an input where the contents don't come from props (or state), that's called an 'uncontrolled component'.  https://reactjs.org/docs/uncontrolled-components.html

For example, if you only want to write the data to the store once the input loses focus, something like this works:

```jsx
const App = ({ store }) => {
  const ref = useRef();
  return (
    <div className="App">
      <textarea
        ref={ref}
        onBlur={e => {
          store.code = ref.current.value;
        }}
      />

      <hr />

      <pre>{JSON.stringify(store, null, 2)}</pre>
    </div>
  );
};
```

CodeSandbox: https://codesandbox.io/s/recollect-issue-90-3i9v9

**Comment by Kycermann** [comment]
Thank you for getting back to me. This is a text area that has a default value from the state- but this value changes when the user switches tabs. I've created pull request #91 that attempts to solve this.

**Comment by Kycermann** [comment]
> How do I go about preventing the re-rendering using react-recollect?

As discussed in pull request #91 this feature would do more harm than help.

**Comment by davidgilbertson** [comment]
FYI @Kycermann I've been checking out `CodeMirror` to see if there's any compatibility issues in general, and all looks OK. Performance is great with this setup (controlled component), including external changes updating the code.

```jsx
import React from 'react';
import { Controlled as CodeMirror } from 'react-codemirror2';
import 'codemirror/lib/codemirror.css';
import 'codemirror/theme/material.css';
import 'codemirror/mode/javascript/javascript';
import { collect, initStore } from 'react-recollect';
import './styles.css';

initStore({
  value: `const foo = 'bar'`
});

const App = ({ store }) => (
  <React.Fragment>
    <button
      onClick={() => (store.value = `// This is a comment\n${store.value}`)}
    >
      Prepend comment
    </button>

    <CodeMirror
      options={{
        mode: 'javascript',
        theme: 'material'
      }}
      value={store.value}
      onBeforeChange={(editor, data, value) => {
        store.value = value;
      }}
    />
  </React.Fragment>
);

export default collect(App);
```

https://codesandbox.io/s/codemirror-example-1r1u6
